export interface Therapist {
  id: number;
  name: string;
  role: string;
  experience: string;
  hours: string;
  tags: string[];
  image: string;
  nextSlot: string;
  price: number;
  progress: string; // "1/3"
  audioDuration: string;
}

export const therapists: Therapist[] = [
  {
    id: 1,
    name: "Celina Binu",
    role: "Consultant Psychologist",
    experience: "5 years exp",
    hours: "450+ Therapy Hours",
    tags: ["Stress", "Relationships"],
    image: "https://i.pravatar.cc/150?u=expert1",
    nextSlot: "Tomorrow, 10:00 AM",
    price: 1500,
    progress: "1/3",
    audioDuration: "1:47",
  },
  {
    id: 2,
    name: "Dr. Ria",
    role: "Clinical Psychologist",
    experience: "7 years exp",
    hours: "750+ Therapy Hours",
    tags: ["Anxiety", "Depression", "OCD"],
    image: "https://i.pravatar.cc/150?u=expert2",
    nextSlot: "Tomorrow, 2:00 PM",
    price: 1800,
    progress: "2/5",
    audioDuration: "2:15",
  },
  {
    id: 3,
    name: "Leena Mary Mathew",
    role: "Consultant Psychologist",
    experience: "6 years exp",
    hours: "600+ Therapy Hours",
    tags: ["Trauma", "Self-esteem"],
    image: "https://i.pravatar.cc/150?u=expert3",
    nextSlot: "Today, 5:00 PM",
    price: 1600,
    progress: "1/2",
    audioDuration: "1:30",
  },
  {
    id: 4,
    name: "Gayathri R",
    role: "Clinical Psychologist",
    experience: "4 years exp",
    hours: "380+ Therapy Hours",
    tags: ["Anger", "Work Stress"],
    image: "https://i.pravatar.cc/150?u=expert3",
    nextSlot: "Today, 11:00 AM",
    price: 1400,
    progress: "1/4",
    audioDuration: "2:00",
  },
  {
    id: 5,
    name: "Anoohya",
    role: "Consultant Psychologist",
    experience: "8 years exp",
    hours: "920+ Therapy Hours",
    tags: ["PTSD", "Grief", "Loss"],
    image: "https://i.pravatar.cc/150?u=expert4",
    nextSlot: "Tomorrow, 3:00 PM",
    price: 1200,
    progress: "3/5",
    audioDuration: "1:55",
  },
  {
    id: 6,
    name: "Dr. Hariharan Shanmugam",
    role: "Psychiatrist",
    experience: "12 years exp",
    hours: "1500+ Therapy Hours",
    tags: ["Bipolar", "Schizophrenia"],
    image: "https://i.pravatar.cc/150?u=expert5",
    nextSlot: "Tomorrow, 9:00 AM",
    price: 2500,
    progress: "2/3",
    audioDuration: "2:30",
  },
  {
    id: 7,
    name: "Noor Fathima",
    role: "Clinical Psychologist",
    experience: "5 years exp",
    hours: "520+ Therapy Hours",
    tags: ["Parenting", "Family Issues"],
    image: "https://i.pravatar.cc/150?u=expert7",
    nextSlot: "Tomorrow, 6:00 PM",
    price: 1550,
    progress: "1/3",
    audioDuration: "1:40",
  },
  {
    id: 8,
    name: "Blessy Mariya Mathew",
    role: "Consultant Psychologist",
    experience: "6 years exp",
    hours: "670+ Therapy Hours",
    tags: ["Addiction", "Substance Abuse"],
    image: "https://i.pravatar.cc/150?u=expert8",
    nextSlot: "Tomorrow, 1:00 PM",
    price: 1770,
    progress: "2/5",
    audioDuration: "2:10",
  },
  {
    id: 9,
    name: "Dr. Swetha P B",
    role: "Clinical Psychologist",
    experience: "4 years exp",
    hours: "1100+ Therapy Hours",
    tags: ["Eating Disorders", "Body Image"],
    image: "https://i.pravatar.cc/150?u=expert9",
    nextSlot: "Today, 4:00 PM",
    price: 1900,
    progress: "1/2",
    audioDuration: "1:50",
  },
  {
    id: 10,
    name: "Darsha Vijayan",
    role: "Consultant Psychologist",
    experience: "4 years exp",
    hours: "410+ Therapy Hours",
    tags: ["Career", "Life Transitions"],
    image: "https://i.pravatar.cc/150?u=expert10",
    nextSlot: "Tomorrow, 3:30 PM",
    price: 1450,
    progress: "1/3",
    audioDuration: "1:45",
  },
];
